### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by iimog** [molbiodiv/fennec#128]
We received reviewer comments for our manuscript. The reviewers raise a lot of important and valid points many of them related to usability of the FENNEC. This is a meta-issue collecting those points and tracking the progress:
- [x] better data upload/alternatives to BIOM
- [x] better documentation on upload/tutorial (#129)
- [x] Github Docu not well organized/clear
- [x] Mac Installation fails (#130)
- [x] API doc missing (#100)
- [x] scientist trait data inclusion
- [x] (more data)
- [x] a lot of minor textual changes
- [x] Figure and case study rework
